/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/
-- Find the total customers by countries
SELECT 
COUNT(customer_key) AS total_customer, 
country FROM gold.dim_customers 
GROUP BY Country 
ORDER BY total_customer DESC
-- Find the total customers by gender
SELECT 
COUNT(customer_key) AS total_customer, 
gender FROM gold.dim_customers 
GROUP BY gender 
ORDER BY total_customer DESC
-- Find the total products by category
SELECT 
COUNT(product_key) AS total_product, 
category FROM gold.dim_products 
GROUP BY category 
ORDER BY total_product DESC
-- What is the average cost in each category?
SELECT AVG(cost) AS avg_cost , 
category FROM gold.dim_products 
GROUP BY category 
ORDER BY avg_cost DESC
-- What is the total revenue generated for each category?
SELECT 
SUM(f.sales_amount) AS total_revenue, 
p.category 
FROM gold.fact_sales f 
JOIN gold.dim_products p ON p.product_key = f.product_key 
GROUP BY category 
ORDER BY total_revenue DESC
-- Find total revenue is generated by each customer
SELECT 
SUM(sales_amount) AS total_revenue,
customer_key FROM gold.fact_sales 
GROUP BY customer_key 
ORDER BY total_revenue DESC
-- What is the distribution of sold items across countries?
SELECT SUM(quantity) AS items_sold, 
c.country FROM gold.fact_sales s 
JOIN gold.dim_customers c ON s.customer_key = c.customer_key  
GROUP BY country 
ORDER BY items_sold DESC
